// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jENqvBHbRPXMByDQmRe4G7
// Component: fxr9ZT31qRP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Menu from "../../Menu"; // plasmic-import: 5tZNLUygwX/component
import ButtonExternalLink from "../../ButtonExternalLink"; // plasmic-import: zlKX0iG_vm/component
import Footer from "../../Footer"; // plasmic-import: hB94XRzTpm/component

import { useScreenVariants as useScreenVariantsjnTclXkDzSl7V } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jnTCLXkDZSl7V/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_build_systems.module.css"; // plasmic-import: jENqvBHbRPXMByDQmRe4G7/projectcss
import sty from "./PlasmicProjekte.module.css"; // plasmic-import: fxr9ZT31qRP/css

export type PlasmicProjekte__VariantMembers = {};
export type PlasmicProjekte__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjekte__VariantsArgs;
export const PlasmicProjekte__VariantProps = new Array<VariantPropType>();

export type PlasmicProjekte__ArgsType = {};
type ArgPropType = keyof PlasmicProjekte__ArgsType;
export const PlasmicProjekte__ArgProps = new Array<ArgPropType>();

export type PlasmicProjekte__OverridesType = {
  root?: p.Flex<"div">;
  menu?: p.Flex<typeof Menu>;
  img?: p.Flex<typeof p.PlasmicImg>;
  buttonExternalLink?: p.Flex<typeof ButtonExternalLink>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultProjekteProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjekte__RenderFunc(props: {
  variants: PlasmicProjekte__VariantsArgs;
  args: PlasmicProjekte__ArgsType;
  overrides: PlasmicProjekte__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjnTclXkDzSl7V()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicProjekte.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProjekte.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProjekte.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicProjekte.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicProjekte.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicProjekte.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__dZcGt)}>
            <Menu
              data-plasmic-name={"menu"}
              data-plasmic-override={overrides.menu}
              className={classNames("__wab_instance", sty.menu)}
              test={["projekte"]}
            />
          </div>
          {true ? (
            <div
              className={classNames(
                projectcss.all,
                sty.freeBox__hLiSh,
                "blend" as const
              )}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jGp,
                  "blend" as const
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Build "
                  : "Build"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hcY7E,
                  ``
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Systems"
                  : "Systems"}
              </div>
            </div>
          ) : null}
          <div className={classNames(projectcss.all, sty.freeBox__iedGv)}>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__nDwJx)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qrqk5
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpl\u00e4ne). Hierf\u00fcr stellen wir Nachhaltigkeitsanforderungen der individuellen Projektentwicklung \u00f6konomischen Indikatoren gegen\u00fcber. Wir unterst\u00fctzen Immobilienentwickler:innen in einer fr\u00fchen Phase der Planung Investitionsentscheidungen zu treffen."
                    : "Wie viel Nachhaltigkeit m\u00f6chten Sie planen und umsetzen?\n       Wir stellen die relevanten Entscheidungsgrundlagen bereit, damit Sie den effizientesten\nEntwicklungspfad w\u00e4hlen, schlagkr\u00e4ftige Ma\u00dfnahmen ansto\u00dfen und Stakeholder koordinieren k\u00f6nnen."}
                </div>
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__joj1B)} />

          <div className={classNames(projectcss.all, sty.freeBox___7Ju0Z)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oOtS
              )}
            >
              {"beh\u00e4lt Bedarfe im Blick."}
            </div>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___1Rbvf)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__yDqAx)}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___0UNlN)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3FqJk
                    )}
                  >
                    {"Worauf Sie ein Auge haben sollten."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zl0Ru
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpl\u00e4ne). Hierf\u00fcr stellen wir Nachhaltigkeitsanforderungen der individuellen Projektentwicklung \u00f6konomischen Indikatoren gegen\u00fcber. Wir unterst\u00fctzen Immobilienentwickler:innen in einer fr\u00fchen Phase der Planung Investitionsentscheidungen zu treffen."
                      : "Wir identifizieren die wichtigsten Stellschrauben und zeigen auf, welche Kriterien zu vernachl\u00e4ssigen sind. Sie schaffen Trade-offs in der Emissionsreduktion und w\u00e4hlen die effektivsten Ma\u00dfnahmen.\n      Das ist unser systemischer Ansatz: Sie wissen genau, worauf Sie sich einlassen, welche Akteure im weiteren Verlauf zu beteiligen sind und welche Geb\u00e4udeeigenschaften Ihre Planung herstellen muss."}
                  </div>
                </div>
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zncCq)} />

          <div className={classNames(projectcss.all, sty.freeBox__waug1)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kzA69
              )}
            >
              {"arbeitet mit dezidierte Benchmarks die bew\u00e4hrt sind."}
            </div>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__bNJw7)}>
                <div className={classNames(projectcss.all, sty.freeBox__geR9R)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fuIkf
                    )}
                  >
                    {"Wissen, was wirklich hilft!"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__myIco
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpl\u00e4ne). Hierf\u00fcr stellen wir Nachhaltigkeitsanforderungen der individuellen Projektentwicklung \u00f6konomischen Indikatoren gegen\u00fcber. Wir unterst\u00fctzen Immobilienentwickler:innen in einer fr\u00fchen Phase der Planung Investitionsentscheidungen zu treffen."
                      : "Sie legen Zielvereinbarungen fest. Wir vergleichen Szenarien zu Bedarfsplanung und Energiebetrachtung und pr\u00fcfen Planungsans\u00e4tze hinsichtlich ihrer ESG-Performance. Wir legen die jeweiligen Aussichten auf Zertifizierungen und F\u00f6rderungen nachvollziehbar dar und zeigen Pfade zu Emissions- und\nKostenzielen auf."}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8P12K)}
                />
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__bza1F)} />

          <div className={classNames(projectcss.all, sty.freeBox___1BCe)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w7WU
              )}
            >
              {"erstellt Vordimensionierungen zu #Anlagentechnik."}
            </div>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___01G1C)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___45NO)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__wwFi)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3DAvc
                    )}
                  >
                    {"Wo die Reise hingeht:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7UGbo
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpl\u00e4ne). Hierf\u00fcr stellen wir Nachhaltigkeitsanforderungen der individuellen Projektentwicklung \u00f6konomischen Indikatoren gegen\u00fcber. Wir unterst\u00fctzen Immobilienentwickler:innen in einer fr\u00fchen Phase der Planung Investitionsentscheidungen zu treffen."
                      : "Sie m\u00f6chten fr\u00fchzeitig im Prozess die entscheidenden Weichen stellen und Umplanungen vermeiden? Durch integrale Planung bilden wir technische Rahmenbedingungen bis zu einer Detailtiefe des Wandaufbaus ab und \u00fcbersetzen Anforderungen und Benchmarks in realistische Umsetzungsstrategien."}
                  </div>
                </div>
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__k2Js7)} />

          <div className={classNames(projectcss.all, sty.freeBox__utoOc)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jbiaA
              )}
            >
              {"steigerte durch abgestimmte Prozesse baulichen Mehrwert"}
            </div>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__pp7Rp)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__pbqBv)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__dOc2)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__muU5O
                    )}
                  >
                    {"Wo die Reise hingeht:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kwBke
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpl\u00e4ne). Hierf\u00fcr stellen wir Nachhaltigkeitsanforderungen der individuellen Projektentwicklung \u00f6konomischen Indikatoren gegen\u00fcber. Wir unterst\u00fctzen Immobilienentwickler:innen in einer fr\u00fchen Phase der Planung Investitionsentscheidungen zu treffen."
                      : "Sie m\u00f6chten fr\u00fchzeitig im Prozess die entscheidenden Weichen stellen und Umplanungen vermeiden? Durch integrale Planung bilden wir technische Rahmenbedingungen bis zu einer Detailtiefe des Wandaufbaus ab und \u00fcbersetzen Anforderungen und Benchmarks in realistische Umsetzungsstrategien."}
                  </div>
                </div>
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zuP9R)} />

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__qnFVu, ``)}>
              <div className={classNames(projectcss.all, sty.freeBox__ugd56)}>
                <p.PlasmicImg
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(sty.img)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  src={{
                    src: "/plasmic/build_systems/images/desktopRenderingjpg.jpg",
                    fullWidth: 3146,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__iLvjN)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__pcmGv)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1AAp7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kwO7A
                      )}
                    >
                      {"Sie haben eine weitere Frage?"}
                    </div>
                    <ButtonExternalLink
                      data-plasmic-name={"buttonExternalLink"}
                      data-plasmic-override={overrides.buttonExternalLink}
                      className={classNames(
                        "__wab_instance",
                        sty.buttonExternalLink
                      )}
                      link={"mailto:mail@buildsystems.de" as const}
                    >
                      {"Schreiben Sie uns eine Mail!"}
                    </ButtonExternalLink>
                  </div>
                </div>
              </div>
              <Footer
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames("__wab_instance", sty.footer)}
              />
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "menu", "img", "buttonExternalLink", "footer"],
  menu: ["menu"],
  img: ["img"],
  buttonExternalLink: ["buttonExternalLink"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  menu: typeof Menu;
  img: typeof p.PlasmicImg;
  buttonExternalLink: typeof ButtonExternalLink;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjekte__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjekte__VariantsArgs;
    args?: PlasmicProjekte__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjekte__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProjekte__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProjekte__ArgProps,
          internalVariantPropNames: PlasmicProjekte__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjekte__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjekte";
  } else {
    func.displayName = `PlasmicProjekte.${nodeName}`;
  }
  return func;
}

export const PlasmicProjekte = Object.assign(
  // Top-level PlasmicProjekte renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menu: makeNodeComponent("menu"),
    img: makeNodeComponent("img"),
    buttonExternalLink: makeNodeComponent("buttonExternalLink"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicProjekte
    internalVariantProps: PlasmicProjekte__VariantProps,
    internalArgProps: PlasmicProjekte__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Build Systems",
      description:
        "Build Systems entwickelt individuelle Smart Sustainability Roadmaps (Nachhaltigkeits-fahrpläne).  Wir unterstützen Immobilienentwickler:innen in einer frühen Phase der Planung.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProjekte;
/* prettier-ignore-end */
