// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
    PlasmicLottieScroll,
    DefaultLottieScrollProps
} from "./plasmic/build_systems/PlasmicLottieScroll";
import {HTMLElementRefOf} from "@plasmicapp/react-web";
import Lottie, {useLottie, useLottieInteractivity} from "lottie-react";
// import the likeButton.json form the public folder
import animation from "../public/likeButton.json";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface LottieScrollProps extends Omit<DefaultLottieScrollProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultLottieScrollProps altogether and have
// total control over the props for your component.
export interface LottieScrollProps extends DefaultLottieScrollProps {
}

function LottieScroll_(props: LottieScrollProps, ref: HTMLElementRefOf<"div">) {
    const options = {
        animationData: animation,
    };
   /* const Example = () => {
        const lottieObj = useLottie(options);
        const Animation = useLottieInteractivity({
            lottieObj,
            mode: "scroll",
            actions: [
                {
                    visibility: [0, 0.45],
                    type: "stop",
                    frames: [0],
                },
                {
                    visibility: [0.45, 1],
                    type: "seek",
                    frames: [0, 38],
                },
            ],
        });

        return Animation;
    };*/

    return (
        <PlasmicLottieScroll root={{ ref }} {...props}>

        </PlasmicLottieScroll>
    );
}

const LottieScroll = React.forwardRef(LottieScroll_);
export default LottieScroll;
